server:
  applicationConnectors:
    - type: http
      port: 8084
  adminConnectors:
    - type: http
      port: 8085

logging:
  level: INFO
  loggers:
    io.dropwizard: INFO
    com.vimond : DEBUG
  appenders:
    - type: console

vimond-api:
  endpoint: vimond-rest-api.ha.expo-first.vimondtv.com
  port: 443